import { Feather, Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useColors } from '@/hooks/useColors';
import { useStore } from '@/lib/store';
import { PrimaryButton, Screen } from '@/components/ui';
export default function AuthScreen() {
  const colors = useColors(); const { setUser } = useStore(); const [register, setRegister] = useState(false); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const submit = () => { if (!email.includes('@') || password.length < 4 || (register && name.trim().length < 2)) { Alert.alert('Check your details', register ? 'Add your name, a valid email, and a 4-character password.' : 'Enter a valid email and password.'); return; } setUser({ name: register ? name.trim() : email.split('@')[0], email: email.trim() }); router.back(); };
  return <Screen scroll={false} style={styles.screen}><View style={[styles.mark, { backgroundColor: colors.primary }]}><Ionicons name="flame" size={28} color={colors.primaryForeground}/></View><Text style={[styles.kicker, { color: colors.accent }]}>BUN & BITE</Text><Text style={[styles.title, { color: colors.foreground }]}>{register ? 'Make it yours.' : 'Welcome back.'}</Text><Text style={[styles.copy, { color: colors.mutedForeground }]}>{register ? 'Save favorites, addresses, and your after-dark order history.' : 'Your next good decision is only a few taps away.'}</Text><View style={{ gap: 10, marginTop: 25 }}>{register && <Field icon="user" placeholder="Your name" value={name} onChangeText={setName} colors={colors}/>}<Field icon="mail" placeholder="Email address" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" colors={colors}/><Field icon="lock" placeholder="Password" value={password} onChangeText={setPassword} secureTextEntry colors={colors}/></View><View style={{ marginTop: 18 }}><PrimaryButton label={register ? 'Create account' : 'Sign in'} onPress={submit} icon="arrow-right"/></View><Pressable onPress={() => setRegister(!register)} style={styles.switch}><Text style={[styles.switchText, { color: colors.mutedForeground }]}>{register ? 'Already have an account?' : 'New to Bun & Bite?'}</Text><Text style={[styles.switchLink, { color: colors.primary }]}>{register ? ' Sign in' : ' Create account'}</Text></Pressable><Pressable onPress={() => router.back()} style={styles.guest}><Feather name="arrow-left" size={15} color={colors.mutedForeground}/><Text style={[styles.guestText, { color: colors.mutedForeground }]}>Continue as guest</Text></Pressable></Screen>;
}
function Field({ icon, placeholder, value, onChangeText, colors, ...rest }: { icon: any; placeholder: string; value: string; onChangeText: (value: string) => void; colors: ReturnType<typeof useColors>; [key: string]: any }) { return <View style={[styles.field, { backgroundColor: colors.card, borderColor: colors.border }]}><Feather name={icon} size={17} color={colors.mutedForeground}/><TextInput {...rest} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={colors.mutedForeground} style={[styles.input, { color: colors.foreground }]}/></View>; }
const styles = StyleSheet.create({ screen: { paddingTop: 48 }, mark: { width: 58, height: 58, borderRadius: 20, alignItems: 'center', justifyContent: 'center', marginBottom: 18 }, kicker: { fontFamily: 'Inter_700Bold', fontSize: 11, letterSpacing: 1.8 }, title: { fontFamily: 'Inter_700Bold', fontSize: 31, letterSpacing: -.8, marginTop: 10 }, copy: { fontFamily: 'Inter_400Regular', fontSize: 14, lineHeight: 21, marginTop: 7 }, field: { height: 53, borderWidth: 1, borderRadius: 15, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, gap: 10 }, input: { flex: 1, fontFamily: 'Inter_400Regular', fontSize: 14 }, switch: { flexDirection: 'row', justifyContent: 'center', marginTop: 22 }, switchText: { fontFamily: 'Inter_400Regular', fontSize: 12 }, switchLink: { fontFamily: 'Inter_700Bold', fontSize: 12 }, guest: { position: 'absolute', bottom: 35, alignSelf: 'center', flexDirection: 'row', gap: 6, alignItems: 'center' }, guestText: { fontFamily: 'Inter_600SemiBold', fontSize: 12 } });