import { Feather, Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useColors } from '@/hooks/useColors';
import { PrimaryButton, Screen } from '@/components/ui';
export default function ConfirmationScreen() {
  const colors = useColors(); const { id, total, type } = useLocalSearchParams<{ id: string; total: string; type: string }>();
  return <Screen scroll={false} style={styles.screen}><View style={[styles.check, { backgroundColor: colors.accent }]}><Feather name="check" size={35} color={colors.accentForeground}/></View><Text style={[styles.kicker, { color: colors.accent }]}>ORDER CONFIRMED</Text><Text style={[styles.title, { color: colors.foreground }]}>That’s a wrap.</Text><Text style={[styles.copy, { color: colors.mutedForeground }]}>We’re on it. Your {type?.toLowerCase()} order will be ready before the craving fades.</Text><View style={[styles.ticket, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.ticketTop}><View><Text style={[styles.ticketLabel, { color: colors.mutedForeground }]}>ORDER NUMBER</Text><Text style={[styles.orderId, { color: colors.foreground }]}>{id}</Text></View><Ionicons name="flame" size={22} color={colors.primary}/></View><View style={[styles.divider, { borderColor: colors.border }]}/><View style={styles.ticketBottom}><Text style={[styles.ticketLabel, { color: colors.mutedForeground }]}>TOTAL PAID</Text><Text style={[styles.amount, { color: colors.primary }]}>${total}</Text></View></View><View style={[styles.next, { backgroundColor: colors.secondary }]}><Ionicons name={type === 'Pickup' ? 'storefront-outline' : 'bicycle-outline'} size={22} color={colors.accent}/><View style={{ flex: 1 }}><Text style={[styles.nextTitle, { color: colors.foreground }]}>{type === 'Pickup' ? 'Ready in 15–20 minutes' : 'Arriving in 30–40 minutes'}</Text><Text style={[styles.nextCopy, { color: colors.mutedForeground }]}>We’ll keep your order history updated.</Text></View></View><View style={{ marginTop: 20 }}><PrimaryButton label="Back to home" onPress={() => router.replace('/')} icon="home"/></View><Pressable onPress={() => router.replace('/orders')} style={styles.ordersLink}><Text style={[styles.ordersText, { color: colors.primary }]}>View order history</Text><Feather name="arrow-up-right" size={14} color={colors.primary}/></Pressable></Screen>;
}
const styles = StyleSheet.create({ screen: { alignItems: 'center', paddingTop: 65 }, check: { width: 77, height: 77, borderRadius: 28, alignItems: 'center', justifyContent: 'center', marginBottom: 23 }, kicker: { fontFamily: 'Inter_700Bold', fontSize: 11, letterSpacing: 1.6 }, title: { fontFamily: 'Inter_700Bold', fontSize: 34, marginTop: 10 }, copy: { fontFamily: 'Inter_400Regular', fontSize: 14, lineHeight: 21, textAlign: 'center', marginTop: 7, maxWidth: 300 }, ticket: { width: '100%', borderRadius: 20, borderWidth: 1, padding: 17, marginTop: 28 }, ticketTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, ticketLabel: { fontFamily: 'Inter_700Bold', fontSize: 9, letterSpacing: 1.1 }, orderId: { fontFamily: 'Inter_700Bold', fontSize: 18, marginTop: 5 }, divider: { borderTopWidth: 1, borderStyle: 'dashed', marginVertical: 16 }, ticketBottom: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, amount: { fontFamily: 'Inter_700Bold', fontSize: 21 }, next: { width: '100%', borderRadius: 17, padding: 15, marginTop: 12, flexDirection: 'row', alignItems: 'center', gap: 11 }, nextTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 13 }, nextCopy: { fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 3 }, ordersLink: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 18 }, ordersText: { fontFamily: 'Inter_700Bold', fontSize: 12 } });