export type Category = 'burgers' | 'drinks' | 'family' | 'sides' | 'desserts';
export type Product = {
  id: number; name: string; image: any; category: Category; price: number; oldPrice?: number;
  rating: string; reviews: string; time: string; calories: string; description: string;
  sizes?: { label: string; price: number }[]; addOns?: string[]; badge: string;
};

const img = (path: string) => ({ uri: path });
export const PRODUCTS: Product[] = [
  { id: 1, name: 'The Classic Burger', image: require('../assets/images/classic.jpg'), category: 'burgers', price: 5.89, oldPrice: 25.99, rating: '4.9', reviews: '365', time: '10m', calories: '850 cal', badge: 'SIGNATURE', description: 'A juicy grilled beef patty layered with fresh lettuce, cheese, and signature sauce inside a soft toasted bun.', sizes: [{ label: 'Regular', price: 0 }, { label: 'Double', price: 2.5 }], addOns: ['Extra Cheese', 'Extra Patty', 'No Sauce', 'Extra Sauce', 'Jalapeños'] },
  { id: 2, name: 'Smoky BBQ Burger', image: require('../assets/images/smoky.jpg'), category: 'burgers', price: 6.75, oldPrice: 10.78, rating: '4.9', reviews: '—', time: '12m', calories: '650 cal', badge: 'HOT', description: 'Grilled beef topped with smoky BBQ sauce, crispy onions, and melted cheddar.', sizes: [{ label: 'Regular', price: 0 }, { label: 'Double', price: 2.5 }], addOns: ['Extra Cheese', 'Extra Patty', 'No Sauce', 'Jalapeños'] },
  { id: 3, name: 'Spicy Fire Burger', image: require('../assets/images/spicy.jpg'), category: 'burgers', price: 10.89, oldPrice: 15.98, rating: '4.8', reviews: '405', time: '12m', calories: '650 cal', badge: 'HOT', description: 'A fiery flavor-packed burger with melted cheese, fresh jalapeños, and rich spicy sauce.', sizes: [{ label: 'Regular', price: 0 }, { label: 'Double', price: 2.5 }], addOns: ['Extra Cheese', 'Extra Patty', 'Extra Sauce', 'Jalapeños'] },
  { id: 4, name: 'Crispy Chicken Burger', image: require('../assets/images/chicken.jpg'), category: 'burgers', price: 8.75, oldPrice: 10.78, rating: '4.9', reviews: '405', time: '12m', calories: '850 cal', badge: 'POPULAR', description: 'A perfectly crispy golden-fried chicken fillet with lettuce and creamy mayo.', sizes: [{ label: 'Regular', price: 0 }, { label: 'Double', price: 2.5 }], addOns: ['Extra Cheese', 'Extra Patty', 'No Sauce', 'Jalapeños'] },
  { id: 5, name: 'Classic Cola', image: require('../assets/images/menu/drinks/cola.png'), category: 'drinks', price: 2.49, oldPrice: 3.99, rating: '4.8', reviews: '210', time: '1m', calories: '140 cal', badge: 'POPULAR', description: 'Ice-cold classic cola with the perfect balance of sweetness and fizz.', sizes: [{ label: 'Small', price: 0 }, { label: 'Medium', price: .5 }, { label: 'Large', price: 1 }], addOns: ['Extra Ice', 'Lemon Slice', 'No Ice'] },
  { id: 6, name: 'Iced Tea Lemon', image: require('../assets/images/menu/drinks/icedtea.png'), category: 'drinks', price: 2.99, oldPrice: 4.49, rating: '4.7', reviews: '156', time: '1m', calories: '90 cal', badge: 'SIGNATURE', description: 'Freshly brewed iced tea infused with real lemon and a hint of mint.', sizes: [{ label: 'Small', price: 0 }, { label: 'Medium', price: .5 }, { label: 'Large', price: 1 }], addOns: ['Extra Ice', 'Lemon Slice', 'Mint Leaves'] },
  { id: 7, name: 'Strawberry Milkshake', image: require('../assets/images/menu/drinks/milkshake.png'), category: 'drinks', price: 4.49, oldPrice: 5.99, rating: '4.9', reviews: '312', time: '3m', calories: '420 cal', badge: 'CREAMY', description: 'Thick, creamy strawberry milkshake blended with real fruit.', sizes: [{ label: 'Regular', price: 0 }, { label: 'Large', price: 1 }], addOns: ['Extra Whipped Cream', 'Chocolate Drizzle', 'Oreo Crumbs'] },
  { id: 8, name: 'Fresh Orange Juice', image: require('../assets/images/menu/drinks/orangejuice.png'), category: 'drinks', price: 3.49, oldPrice: 4.99, rating: '4.8', reviews: '189', time: '2m', calories: '120 cal', badge: 'FRESH', description: '100% freshly squeezed oranges, no added sugar.', sizes: [{ label: 'Small', price: 0 }, { label: 'Medium', price: .5 }, { label: 'Large', price: 1 }], addOns: ['Extra Ice', 'Pulp', 'No Pulp'] },
  { id: 9, name: 'The Big Feast', image: require('../assets/images/menu/family/feast.png'), category: 'family', price: 24.99, oldPrice: 32.99, rating: '4.9', reviews: '89', time: '20m', calories: '3,200 cal', badge: 'SHARING', description: 'Four burgers, two large fries, four drinks, and a bucket of nuggets.', addOns: ['Extra Sauce Pack', 'Spicy Upgrade', 'Dessert Add-on'] },
  { id: 10, name: 'Double Stack Combo', image: require('../assets/images/menu/family/doublestack.png'), category: 'family', price: 18.99, oldPrice: 24.99, rating: '4.8', reviews: '124', time: '15m', calories: '2,100 cal', badge: 'VALUE', description: 'Two stacked burgers, two sides, and two drinks for a hungry pair.', addOns: ['Extra Sauce Pack', 'Spicy Upgrade', 'Extra Fries'] },
  { id: 11, name: 'Chicken Lovers Box', image: require('../assets/images/menu/family/chickenlovers.png'), category: 'family', price: 19.99, oldPrice: 26.99, rating: '4.7', reviews: '67', time: '18m', calories: '2,400 cal', badge: 'PREMIUM', description: 'Eight nuggets, two chicken burgers, large fries, coleslaw, and dips.', addOns: ['Extra Sauce Pack', 'Spicy Upgrade', 'Extra Fries'] },
  { id: 12, name: 'Mega Bundle', image: require('../assets/images/menu/family/megabundle.png'), category: 'family', price: 29.99, oldPrice: 39.99, rating: '4.9', reviews: '203', time: '25m', calories: '4,500 cal', badge: 'BEST VALUE', description: 'Six burgers, three large fries, onion rings, drinks, nuggets, and desserts.', addOns: ['Extra Sauce Pack', 'Dessert Add-on', 'Extra Fries'] },
  { id: 13, name: 'Classic Fries', image: require('../assets/images/menu/sides/fries.png'), category: 'sides', price: 2.99, oldPrice: 4.49, rating: '4.8', reviews: '452', time: '5m', calories: '320 cal', badge: 'POPULAR', description: 'Golden, crispy, perfectly salted fries cut fresh daily.', sizes: [{ label: 'Regular', price: 0 }, { label: 'Large', price: 1.5 }], addOns: ['Cheese Sauce', 'Chili Topping', 'Truffle Oil'] },
  { id: 14, name: 'Crispy Onion Rings', image: require('../assets/images/menu/sides/onionrings.png'), category: 'sides', price: 3.49, oldPrice: 4.99, rating: '4.7', reviews: '178', time: '6m', calories: '280 cal', badge: 'CRISPY', description: 'Thick-cut onions in light golden batter with tangy dipping sauce.', sizes: [{ label: 'Regular', price: 0 }, { label: 'Large', price: 1.5 }], addOns: ['Spicy Dip', 'Ranch Dip', 'BBQ Dip'] },
  { id: 15, name: 'Chicken Nuggets (8pc)', image: require('../assets/images/menu/sides/nuggets.png'), category: 'sides', price: 4.99, oldPrice: 6.99, rating: '4.8', reviews: '310', time: '7m', calories: '380 cal', badge: 'KIDS FAV', description: 'Tender juicy chicken in a crunchy golden coating.', sizes: [{ label: '8pc', price: 0 }, { label: '12pc', price: 2 }], addOns: ['Spicy Dip', 'Ranch Dip', 'BBQ Dip'] },
  { id: 16, name: 'Loaded Nachos', image: require('../assets/images/menu/sides/nachos.png'), category: 'sides', price: 5.49, oldPrice: 7.99, rating: '4.6', reviews: '95', time: '8m', calories: '450 cal', badge: 'SHAREABLE', description: 'Crispy tortilla chips smothered in cheese, jalapeños, sour cream, and salsa.', addOns: ['Extra Cheese', 'Guacamole', 'Ground Beef'] },
  { id: 17, name: 'Chocolate Lava Cake', image: require('../assets/images/menu/desserts/lavacake.png'), category: 'desserts', price: 5.99, oldPrice: 8.99, rating: '4.9', reviews: '267', time: '8m', calories: '480 cal', badge: 'SIGNATURE', description: 'Warm decadent chocolate cake with a molten center.', addOns: ['Vanilla Ice Cream', 'Extra Chocolate Sauce', 'Whipped Cream'] },
  { id: 18, name: 'Vanilla Sundae', image: require('../assets/images/menu/desserts/sundae.png'), category: 'desserts', price: 4.49, oldPrice: 6.49, rating: '4.8', reviews: '198', time: '3m', calories: '320 cal', badge: 'CREAMY', description: 'Creamy vanilla soft serve with chocolate drizzle, sprinkles, and a cherry.', addOns: ['Extra Toppings', 'Caramel Drizzle', 'Cookie Crumbles'] },
  { id: 19, name: 'Strawberry Cheesecake', image: require('../assets/images/menu/desserts/cheesecake.png'), category: 'desserts', price: 5.49, oldPrice: 7.99, rating: '4.9', reviews: '145', time: '5m', calories: '420 cal', badge: 'PREMIUM', description: 'Velvety New York-style cheesecake topped with strawberry compote.', addOns: ['Extra Strawberry', 'Chocolate Sauce', 'Whipped Cream'] },
  { id: 20, name: 'Cinnamon Churros', image: require('../assets/images/menu/desserts/churros.png'), category: 'desserts', price: 3.99, oldPrice: 5.99, rating: '4.7', reviews: '112', time: '6m', calories: '350 cal', badge: 'CRISPY', description: 'Warm cinnamon sugar churros served with rich chocolate dipping sauce.', addOns: ['Extra Chocolate Sauce', 'Caramel Dip', 'Ice Cream Pairing'] },
];
export const CATEGORIES: { key: Category; label: string }[] = [
  { key: 'burgers', label: 'Burgers' }, { key: 'drinks', label: 'Drinks' }, { key: 'family', label: 'Family Meal' }, { key: 'sides', label: 'Sides' }, { key: 'desserts', label: 'Desserts' },
];
export const getProduct = (id: number) => PRODUCTS.find((p) => p.id === id);