import { Feather, Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useColors } from '@/hooks/useColors';
import { useStore } from '@/lib/store';
import { BrandHeader, PrimaryButton, Screen, SectionTitle } from '@/components/ui';
export default function OrdersScreen() {
  const colors = useColors(); const { orders } = useStore();
  return <Screen><BrandHeader subtitle="Every bite, accounted for."/><SectionTitle eyebrow="THE PAPER TRAIL" title="Your orders" />{orders.length ? orders.map((order) => <View key={order.id} style={[styles.order, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.orderTop}><View style={[styles.statusDot, { backgroundColor: colors.accent }]}><Ionicons name="checkmark" size={15} color={colors.accentForeground}/></View><View style={{ flex: 1 }}><Text style={[styles.id, { color: colors.foreground }]}>{order.id}</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>{new Date(order.createdAt).toLocaleDateString()} · {order.type}</Text></View><Text style={[styles.total, { color: colors.primary }]}>${order.total.toFixed(2)}</Text></View><Text numberOfLines={1} style={[styles.items, { color: colors.mutedForeground }]}>{order.items.map((item) => `${item.quantity}× ${item.name}`).join(' · ')}</Text><View style={[styles.orderBottom, { borderTopColor: colors.border }]}><Text style={[styles.status, { color: colors.accent }]}>{order.status}</Text><Pressable onPress={() => { order.items.forEach(() => undefined); router.push('/menu'); }}><Text style={[styles.reorder, { color: colors.primary }]}>ORDER AGAIN <Feather name="arrow-up-right" size={13}/></Text></Pressable></View></View>) : <View style={[styles.empty, { borderColor: colors.border }]}><Feather name="clock" size={28} color={colors.accent}/><Text style={[styles.emptyTitle, { color: colors.foreground }]}>No orders yet</Text><Text style={[styles.emptyCopy, { color: colors.mutedForeground }]}>Your late-night legends will show up here.</Text><PrimaryButton label="Browse menu" onPress={() => router.push('/menu')} icon="arrow-right"/></View>}</Screen>;
}
const styles = StyleSheet.create({ order: { borderRadius: 20, borderWidth: 1, padding: 16, marginBottom: 12 }, orderTop: { flexDirection: 'row', alignItems: 'center', gap: 11 }, statusDot: { width: 31, height: 31, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, id: { fontFamily: 'Inter_700Bold', fontSize: 14 }, meta: { fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 3 }, total: { fontFamily: 'Inter_700Bold', fontSize: 16 }, items: { fontFamily: 'Inter_400Regular', fontSize: 12, marginTop: 15 }, orderBottom: { borderTopWidth: 1, marginTop: 15, paddingTop: 13, flexDirection: 'row', justifyContent: 'space-between' }, status: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1 }, reorder: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: .7 }, empty: { borderWidth: 1, borderStyle: 'dashed', borderRadius: 20, padding: 28, alignItems: 'center', marginTop: 28 }, emptyTitle: { fontFamily: 'Inter_700Bold', fontSize: 17, marginTop: 13 }, emptyCopy: { fontFamily: 'Inter_400Regular', fontSize: 13, textAlign: 'center', marginTop: 6, marginBottom: 19 } });