import { Feather, Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { useColors } from '@/hooks/useColors';
import { useStore } from '@/lib/store';
import { BrandHeader, Screen, SectionTitle } from '@/components/ui';
export default function ProfileScreen() {
  const colors = useColors(); const { user, addresses, setUser, orders } = useStore();
  const rows = [{ icon: 'map-pin', title: 'Saved addresses', sub: `${addresses.length} saved`, action: () => router.push('/address') }, { icon: 'clock', title: 'Order history', sub: `${orders.length} orders`, action: () => router.push('/orders') }, { icon: 'help-circle', title: 'Help & support', sub: 'We are here for the late nights', action: () => Alert.alert('Bun & Bite support', 'Chat support is available daily until 2am.') }];
  return <Screen><BrandHeader subtitle="Your Bun & Bite, your way."/><View style={[styles.profileCard, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.avatar, { backgroundColor: colors.primary }]}><Text style={[styles.avatarText, { color: colors.primaryForeground }]}>{user ? user.name.slice(0, 1).toUpperCase() : 'G'}</Text></View><View style={{ flex: 1 }}><Text style={[styles.name, { color: colors.foreground }]}>{user?.name ?? 'Ordering as guest'}</Text><Text style={[styles.email, { color: colors.mutedForeground }]}>{user?.email ?? 'Save your favorites and addresses.'}</Text></View>{user ? <Pressable onPress={() => setUser(null)} hitSlop={10}><Text style={[styles.link, { color: colors.primary }]}>Sign out</Text></Pressable> : <Pressable onPress={() => router.push('/auth')} style={[styles.signIn, { borderColor: colors.primary }]}><Text style={[styles.signInText, { color: colors.primary }]}>Sign in</Text></Pressable>}</View><SectionTitle eyebrow="ACCOUNT" title="Make it yours" />{rows.map((row) => <Pressable key={row.title} onPress={row.action} style={[styles.row, { borderBottomColor: colors.border }]}><View style={[styles.rowIcon, { backgroundColor: colors.secondary }]}><Feather name={row.icon as any} size={19} color={colors.accent}/></View><View style={{ flex: 1 }}><Text style={[styles.rowTitle, { color: colors.foreground }]}>{row.title}</Text><Text style={[styles.rowSub, { color: colors.mutedForeground }]}>{row.sub}</Text></View><Ionicons name="chevron-forward" size={18} color={colors.mutedForeground}/></Pressable>)}<View style={[styles.footerNote, { backgroundColor: colors.secondary }]}><Text style={[styles.footerTitle, { color: colors.foreground }]}>BUN & BITE</Text><Text style={[styles.footerCopy, { color: colors.mutedForeground }]}>Built for cravings after dark.</Text><Text style={[styles.version, { color: colors.mutedForeground }]}>v1.0 · Local checkout mode</Text></View></Screen>;
}
const styles = StyleSheet.create({ profileCard: { flexDirection: 'row', alignItems: 'center', gap: 13, borderRadius: 21, borderWidth: 1, padding: 16, marginTop: 10 }, avatar: { width: 48, height: 48, borderRadius: 17, alignItems: 'center', justifyContent: 'center' }, avatarText: { fontFamily: 'Inter_700Bold', fontSize: 21 }, name: { fontFamily: 'Inter_700Bold', fontSize: 16 }, email: { fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 4 }, link: { fontFamily: 'Inter_700Bold', fontSize: 11 }, signIn: { borderWidth: 1, paddingHorizontal: 12, paddingVertical: 9, borderRadius: 11 }, signInText: { fontFamily: 'Inter_700Bold', fontSize: 12 }, row: { flexDirection: 'row', gap: 13, alignItems: 'center', paddingVertical: 15, borderBottomWidth: 1 }, rowIcon: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, rowTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 14 }, rowSub: { fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 3 }, footerNote: { borderRadius: 18, marginTop: 30, padding: 18 }, footerTitle: { fontFamily: 'Inter_700Bold', fontSize: 12, letterSpacing: 1.5 }, footerCopy: { fontFamily: 'Inter_400Regular', fontSize: 12, marginTop: 7 }, version: { fontFamily: 'Inter_400Regular', fontSize: 10, marginTop: 13 } });